name: Build
on: [push, pull_request]
env:
  PARLAY_NUM_THREADS: 1

jobs:
  msys:
    strategy:
      matrix:
        include:
          - { sys: mingw64 }
          
    name: MSYS2 ${{ matrix.sys }}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On ..

    - name: Build
      run: |
        cd build
        cmake --build .
        time ./test/test_allocator --gtest_list_tests

    - name: Test
      run: |
        cd build
        ctest -C Debug --no-tests=error --output-on-failure
