name: Build
on: [push, pull_request]
env:
  PARLAY_NUM_THREADS: 16

jobs:
  
  msvc:
    name: Microsoft Visual C++
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Configure
      run: |
        md build
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG=" /bigobj " -DPARLAY_TEST=On ..
        
    - name: Build
      run: |
        cd build
        cmake --build .
        
    - name: Test
      run: |
        cd build
        ctest -C Debug --no-tests=error --output-on-failure

  mingw:
    name: MinGW
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: egor-tensin/setup-mingw@v2
    
    - name: Install MinGW
      run: |
        choco install mingw --version=11.2.0
    
    - name: Configure
      run: |
        md build
        cd build
        cmake -G "MinGW Makefiles" -DCMAKE_CC_COMPILER="cc" -DCMAKE_CXX_COMPILER="c++" -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On ..
        
    - name: Build
      run: |
        cd build
        cmake --build .
        
    - name: Test
      run: |
        cd build
        ctest -C Debug --no-tests=error --output-on-failure

  wsl:
    strategy:
      matrix:
        config:
        - {
            name: "WSL GCC-10",
            cc: "gcc-10", cxx: "g++-10"
          }
        - {
            name: "WSL Clang-11",
            cc: "clang-11", cxx: "clang++-11"
          }

    name: ${{ matrix.config.name }}
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-20.04
    
    - name: Install
      shell: wsl-bash {0}
      run: |
        sudo apt-get -qq update
        sudo apt-get -y install make ${{matrix.config.cc}} ${{matrix.config.cxx}}
        wget --quiet https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-Linux-x86_64.tar.gz
        tar -xf cmake-3.18.2-Linux-x86_64.tar.gz
    
    - name: Configure
      shell: wsl-bash {0}
      run: |
        mkdir build
        cd build
        CC=${{matrix.config.cc}} CXX=${{matrix.config.cxx}} ../cmake-3.18.2-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DWSL=True ..
        
    - name: Build
      shell: wsl-bash {0}
      run: |
        cd build
        make
        
    - name: Test
      shell: wsl-bash {0}
      run: |
        cd build
        ../cmake-3.18.2-Linux-x86_64/bin/ctest -C Debug --no-tests=error --output-on-failure
